from decimal import Decimal

MIN_TRANSACTION_AMOUNT = Decimal(0)
MAX_TRANSACTION_AMOUNT = Decimal(10_00_00_00_000)
MAX_TRANSACTION_DIGITS = 25
MAX_TRANSACTION_DECIMALS = 8

INDIAN_UPI_PREFIX_MIN_LENGTH = 2
INDIAN_UPI_SUFFIX_MIN_LENGTH = 2
INDIAN_BANK_ACCOUNT_MIN_LENGTH = 9
INDIAN_BANK_ACCOUNT_MAX_LENGTH = 18
INDIAN_PHONE_NUMBER_MAX_LENGTH = 10
